#!/usr/bin/env python3

import re
import requests
import argparse

email="""
massamba.der@gmail.com
195.18.98.55
034 78 658 69
07 56 96 87 12
AbcecezfzdjiaMZEPCVv
cv  
"""
motif=re.compile(r"([\d]{1,3}\.){3}[0-9]{1,3}")
matches = motif.finditer(email)
for match in matches:
    print(match, match.span(), match.group(), sep="\n")

