#!/usr/bin/env python3
import sys

if len(sys.argv)!=4:
      print("usage: ./test_sys param1 param2 param3")
else:
      print("Le nom de votre programme ou script est contenu dans :",sys.argv[0])
      print("Son nombre d'arguments est :",len(sys.argv)-1)
      print("sys.argv contient ",sys.argv)
      print("Le premier argument est :",sys.argv[1])
      print("Le deuxième argument est :",sys.argv[2])
      print("Le troisième argument est :",sys.argv[3])
      print("Le système d'exploitation (OS) sur lequel est lancé le script est :",sys.platform)
      print("La version de l'interpréteur Python utilisé est :",sys.version)